language: go

go:
  - "1.13"

node_js:
  - "12"

cache:
  yarn: true
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - frontend/node_modules

env:
  global:
    - CGO_ENABLED=0
    - DOCKER_BUILDKIT=1
    - GO111MODULE=on
    - GOBUILD="linux-amd64 windows-amd64 darwin-amd64 linux-arm64"
    - GOPROXY=https://proxy.golang.org

# We depend on Docker 19.03 or newer for per-Dockerfile Dockerignore
# https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - GOBUILD=${GOBUILD} make -j build
  - ls -la backend/build

after_success:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make -j docker TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$TRAVIS_TAG" =~ ^v.*$ ]]; then make -j docker TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make -j docker TAG=latest COMMIT=$TRAVIS_COMMIT; fi

deploy:
  - provider: releases
    api_key:
      secure: JpoLJBxjwzF6KjyxXF2cWL7lVcVjZXYjadhZCHYWC8QVJaJb8N+LxibPU8Cdp08no/QkpM7f8ku64hRVmBz+x39UKRsdmtyablJ5ZyfsfnuhX/cPRyQ9nplzd9r7+LN+u3jgVATm0Egf1VOt7LlZmUg4P0XeezQpdwqfjghSAmpKeUgsW5swaCjyC6fqHM8u9oCTQRdQdtZUvFJ4JkIsNyGDiBJjzAql8gxuZcnM66ihC6jUIi1alb4eSEZ72g5H/L68fkpLr+zb/OfUP0H48gpDm/Cycm17Vi7zntoZQA+fhUtCVMAFzhAC8iefw6PYj/xCBtD5yl7flGr8MXciJs+atd417ErF9h7G9zdLRTTBI/1o2kxOs7VKB19QWINi5Fkm8KxoiI+ttnFnbDlSPyP8jcDw7jcV2Nw6CtwiMgWLXJL4uRw2E7Xucq7pKUuJkl0BAqEvAaZHIia6uQl98j0o/7ZPvMvuQJ5Bq3O6NkRwODXw0iFSzCtqONyDp7VkQKY1jy8EDll5/HjlKFuPUEmRMXM/3YWtZiZfb/RP8t3o+4m7uOOaAvhunEo/756CZmR4kYnebquhzhvlr5IdcdrpNm2F5GwpEFymTO3998/xhZdnScTaACcG0y3MD511TNBR9udfFRKtT44MRtNJ+byPtKKzPDBX+TM8nmaZGvw=
    file:
      - backend/build/hashi-ui-linux-amd64
      - backend/build/hashi-ui-windows-amd64
      - backend/build/hashi-ui-darwin-amd64
      - backend/build/hashi-ui-linux-arm64
    skip_cleanup: true
    overwrite: true
    on:
      repo: jippi/hashi-ui
      tags: true
